# Generated by Django 3.0 on 2019-12-05 09:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LastMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('body_plain', models.TextField()),
                ('body_html', models.TextField()),
                ('date', models.DateTimeField()),
                ('mail_attachments', models.ManyToManyField(to='mails.attachments')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MessageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.UUID('c11fd0d3-bd3a-4ab0-9c4d-a99983695fef'), max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('message', models.ManyToManyField(related_name='messages', to='mails.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.UUID('d0bd5a95-b2b0-4967-ab51-64d46927028c'), max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('full_name', models.CharField(default='', max_length=50)),
                ('personColor', models.CharField(choices=[('#e53935', 'Kırmızı'), ('#1976d2', 'Mavi'), ('#00796b', 'Yeşil'), ('#ffeb3b', 'Sarı'), ('#f4511e', 'Turuncu'), ('#546e7a', 'Gri'), ('#5e35b1', 'Mor')], default='#1976d2', max_length=15)),
                ('is_Super_Person', models.BooleanField(default=False)),
                ('position', models.CharField(default='', max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wait_to_reply', models.ManyToManyField(related_name='incomingemails', to='mails.MessageBlock')),
            ],
        ),
        migrations.AddField(
            model_name='messageblock',
            name='reply_persons',
            field=models.ManyToManyField(related_name='name_persons', to='mails.Person'),
        ),
        migrations.AddField(
            model_name='messageblock',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='mails.Tag'),
        ),
        migrations.AddField(
            model_name='message',
            name='person',
            field=models.ManyToManyField(related_name='name_person', to='mails.Person'),
        ),
    ]
