# Generated by Django 2.2.7 on 2019-12-05 10:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_auto_20191205_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mail_attachments',
            field=models.ManyToManyField(blank=True, to='mails.attachments'),
        ),
        migrations.AlterField(
            model_name='message',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='name_person', to='mails.Person'),
        ),
        migrations.AlterField(
            model_name='messageblock',
            name='reply_persons',
            field=models.ManyToManyField(blank=True, related_name='name_persons', to='mails.Person'),
        ),
        migrations.AlterField(
            model_name='messageblock',
            name='uid',
            field=models.CharField(default=uuid.UUID('eb0321b0-e620-4831-927f-3b68ecf2db59'), max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(default=uuid.UUID('558af49a-555f-4fdc-8a97-f793cc9dedbd'), max_length=50),
        ),
    ]
