# Generated by Django 2.2.7 on 2019-12-05 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_auto_20191205_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageblock',
            old_name='message',
            new_name='messages',
        ),
        migrations.AlterField(
            model_name='messageblock',
            name='uid',
            field=models.CharField(default=uuid.UUID('c025fc27-bdfb-424a-86e6-a865b8abacc8'), max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(default=uuid.UUID('971ecd3e-1997-4c37-a339-2f30704458d4'), max_length=50),
        ),
    ]
