# Generated by Django 2.2.7 on 2019-12-05 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_auto_20191205_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='messageblock',
            name='uid',
            field=models.CharField(default=uuid.UUID('662b596a-b08e-4491-92e9-c2728cbc4aa2'), max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(default=uuid.UUID('50ffee59-a12a-4ba6-8636-b18470e411d7'), max_length=50),
        ),
    ]
