# Generated by Django 2.2.7 on 2019-12-05 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0006_auto_20191205_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterField(
            model_name='messageblock',
            name='uid',
            field=models.CharField(default=uuid.UUID('04aa16d6-d48c-4618-8051-61c184a66b54'), max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(default=uuid.UUID('7fecda88-eb07-4243-9116-fc19608fb803'), max_length=50),
        ),
    ]
