# Generated by Django 2.2.7 on 2019-12-06 14:36

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0007_auto_20191205_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageblock',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='messageblock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='messageblock',
            name='uid',
            field=models.CharField(default=uuid.UUID('3548869f-60da-4c3a-bb7d-3943d1374870'), max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(default=uuid.UUID('6ec435d6-8d0b-4ffe-ac27-5d1cfe4d41c5'), max_length=50),
        ),
    ]
